const express = require('express')
const Router = express.Router()

const employeeRoutes = require('./employee')
const companyRouter = require('./company')
const authController = require('./authCompany')
const portfolioRouter = require('./portfolio')
const hirejob = require('./hirejobs')
const notifikasi = require('./Notifikasi')
const authEmployee = require('./authEmployee')
const employee = require('./employee')
const workExperienceRouter = require('./workExperience')
Router.use('/employee', employeeRoutes)
  .use('/company', companyRouter)
  .use('/portfolio', portfolioRouter)
  .use('/authCompany', authController)
  .use('/hirejob', hirejob)
  .use('/notifikasi', notifikasi)
  .use('/authEmployee', authEmployee)
  .use('/employee', employee)
  .use('/work-experience', workExperienceRouter)
module.exports = Router
